"""CURATE, the writer's second role (spec v2.1 §10.3-10.4, §12.3, D36): when it runs, what it reads, its brief.

**When.** CURATE runs only after a WRITE pass's gate, and only when the library's state warrants it (§10.3):
there are overlap candidates (:mod:`.overlap`), there are ``suspect`` items (P5's item records), or the index the
prompt would carry exceeds ``INDEX_VIEW_TOKENS``. :func:`due` reads one library commit, its records and the
fingerprints earlier CURATE passes were shown. It reads no episode count, stream position or stream boundary.

**Shown once.** Each reason has a fingerprint: an overlap candidate's (:func:`.overlap.fingerprint`); a suspect
item's, from its definition and its reasons; the index's, from the library commit. The driver records the
fingerprints each CURATE pass was shown, whatever its outcome, and :func:`due` returns only those no CURATE pass
has been shown. A candidate CURATE kept apart, or could not resolve, fires again only once its content changes, so
CURATE runs at most once per new library state.

**Inputs** go under ``/inputs/curate/`` (:func:`stage_inputs`). **The brief** is :data:`CURATE_BRIEF_V21`, written
from §10.4 and §12.3; P7 owns its final text, which the lead reviews.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path

from .library_index import INDEX_VIEW_TOKENS

CURATE_DIR = "curate"
# the paths CURATE's brief names (P7's prompts_v21), as stage_inputs writes them
OVERLAPS_INPUT = "/inputs/curate/overlap.json"
SUSPECTS_INPUT = "/inputs/curate/suspects.json"
TRIGGER_INPUT = "/inputs/curate/trigger.json"

#: CURATE's brief (spec §10.4 in prompt form, with §12.3's inputs). A placeholder: P7 writes the reviewed text.
CURATE_BRIEF_V21 = """\
You curate a shared library of tested Python functions and linked markdown notes. A cheaper working model uses
the library while it works. Your job is to keep the library small, correct and easy to navigate. Another pass adds
new work from recordings; you change what is already there.

The library. /memory is a copy of the library's checkout (without git) that you edit; the harness commits it when
you finish. memory/<package>/<module>.py holds functions, memory/<package>/tests/test_<module>.py their tests, and
memory/<package>/tests/data/ their fixtures. notes/<topic>/<slug>.md holds notes; each starts with front matter:
title, description and uses (the functions it relies on). A function's docstring may end with a line
"Notes: <note path>, ...". Those two are the only places a link is written. memory/__init__.py, INDEX.md,
links.json and .memory/ are generated by the harness: read them, never write them. In execute_code,
`import memory` gives memory.index(), memory.show(item) and memory.find(value).

Your inputs, read-only, under /inputs/curate/:
- trigger.json: why this pass runs: overlap candidates, suspect items, or an index longer than its view.
- overlap.json: candidates the harness found from structure and recordings, never from names: functions whose
  recorded input shapes match and whose covers overlap; functions whose bodies anti-unify, with the generalised
  body (each hole is a place where they differ); and notes that use the same set of functions. A candidate is
  evidence, not an order: merge only what does the same job.
- suspects.json: items whose use went wrong in two or more requests (an input check failed, an error was raised,
  or a negative signal followed their use), or that depend on such an item. For each: the requests involved, the
  bisect result (the first version whose behaviour changed on its recorded inputs) and, when an earlier version
  has a clean use record, that version as the proposed rollback target. rollback/ holds its files.
- use.json: how each item was used (imported, called, shown, found), with errors and signals, per library commit.
- history.json: each item's recent changes, as commit and subject.
- aliases.json: the old names kept as aliases, the commit that added each, and whether this pass may remove it.
The requests the suspect items were used in are under /inputs/episodes/; read them with read_episode. The full
result of each gate check of this pass appears under /inputs/gate/. Read with read and grep: every output is
bounded and says where the next part starts.

What to do, most valuable first:
1. Repair or roll back suspect items. Read why each is suspect and the requests involved. Roll back to the
   proposed version when the bisect shows that a later change broke it; otherwise repair it. Either changes
   behaviour, so add a test, from the recorded requests, that fails on the current version and passes on yours.
2. Merge overlapping items into one, keeping each old name working as an alias of the merged function. In the old
   module, bind the old name to it (old = new), import it under the old name
   (from memory.<package>.<module> import new as old), or, when the old function fixed an argument, write a
   one-line wrapper: def old(x): return new(x, <constant>).
3. Generalise variants into one parametric function: the values that differ become parameters, and the old
   functions become aliases of it, as in 2.
4. Retire items that are wrong, or that went unused across many requests, with their tests, giving a reason.
5. Fix broken links, and add missing ones, between notes and the functions they describe.
6. Regroup packages when the index is too long to read at a glance, keeping the old names as aliases.
Leave alone what is fine. Changing nothing is a valid result when no candidate is really one job.

Rules:
- Every behaviour change keeps the library's existing tests green, or retires a test with a stated reason
  (tests_changed).
- A change that keeps behaviour needs no new test. The gate runs each function you change, and every function
  that imports it, on the parent's version and on yours, over their recorded inputs, and the results must agree.
  An existing test that passed on the parent must call each function you edit.
- A change of behaviour needs a test that fails on the parent's library and passes on yours.
- An old name's tests keep testing it through its alias: list them under the merged function's tests.
- A deleted item's recorded inputs stay covered: list them in the covers of the item that takes over its job.
- Do not grow the library: add a function only as the target that old names become aliases of.
- An alias stays until at least one more pass has landed after the pass that added it (aliases.json).
- Never store credentials, session tokens or the results of calls that have effects.

Each execute_code call runs your code as a Python script in a fresh process, with cwd /memory and
PYTHONPATH=/inputs:/memory; only files persist between calls. /memory may hold at most {entries} files and
directories, {file_mib} MiB per file and {total_mib} MiB in all, or the pass is refused. Run tests as the gate
does: subprocess.run([sys.executable, "-m", "pytest", "memory/<package>/tests", "-q", "-p", "no:cacheprovider",
"--rootdir", "/memory", "-c", "/dev/null", "--import-mode=importlib"],
env={"PYTHONPATH": "/memory", "PYTHONDONTWRITEBYTECODE": "1"}).

Finish by writing /memory/.pass/manifest.json (never committed):
{"why": "<one line>", "summary": "<what you did>",
 "items": [{"item": "memory.<package>.<module>:<name>", "kind": "function", "input": "<form>",
            "source_episodes": [...], "tests": [...], "covers": [...]}],
 "deleted": ["<item>", ...], "deleted_tests": ["<test file>", ...],
 "aliases": {"<old item>": "<item it now forwards to>"},
 "retired": {"<deleted item>": "<one-line reason>"},
 "tests_changed": {"<test file, or file::test>": "<one-line reason>"},
 "skeleton": ["memory.<package>.<module>", ...]}
List in items every function you add or change, and the function that takes over an alias's covers and tests.
Every deleted item is either an alias (aliases) or retired with a reason (retired). Name in skeleton each module
whose code outside its functions you change, such as an alias line. Call check(manifest) with the manifest JSON
before finish and fix every reason it returns ({checks} checks per pass at most); then call finish(summary).

You are done when every reason in trigger.json is dealt with or deliberately left as it is, and check(manifest)
returns no reason. After finish the gate runs on your result. If it refuses anything, its full result comes back
to you under /inputs/gate/, and you get another round to repair it.
"""


def curate_system() -> str:
    """CURATE's system message: :data:`CURATE_BRIEF_V21` with the box's bounds filled in."""
    from .sol_pass import MAX_CHECKS, QUOTA_ENTRIES, QUOTA_FILE_BYTES, QUOTA_TOTAL_BYTES

    return (
        CURATE_BRIEF_V21.replace("{entries}", str(QUOTA_ENTRIES))
        .replace("{file_mib}", str(QUOTA_FILE_BYTES // 1024**2))
        .replace("{total_mib}", str(QUOTA_TOTAL_BYTES // 1024**2))
        .replace("{checks}", str(MAX_CHECKS))
    )


@dataclass
class CurateState:
    """What CURATE's trigger and inputs read from one library commit; the driver builds it after WRITE's gate."""

    commit: str
    overlap: dict  # overlap.overlap_candidates(...)
    suspects: dict[
        str,
        dict,
    ]  # P5: item -> {"reasons", "episodes", "bisect", "rollback"}
    index_tokens: (
        int | None
    )  # tokens of the INDEX.md the prompt would carry (None: not built)
    bodies: dict[str, str] = field(
        default_factory=dict,
    )  # item -> unparsed definition (layout.function_bodies)
    use: dict[str, dict] = field(default_factory=dict)  # P5's use records by item
    history: dict[str, list[str]] = field(
        default_factory=dict,
    )  # library_export.item_history
    aliases: dict[str, dict] = field(
        default_factory=dict,
    )  # EvidenceStore.aliases(): the live aliases
    rollback_files: dict[str, dict[str, bytes]] = field(
        default_factory=dict,
    )  # item -> path -> bytes
    fired: dict[str, str] = field(
        default_factory=dict,
    )  # fingerprint -> reason line: why this pass runs


def _canon(obj: object) -> str:
    return json.dumps(
        obj,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
        default=str,
    )


def reasons(state: CurateState, *, budget: int = INDEX_VIEW_TOKENS) -> dict[str, str]:
    """fingerprint -> reason line, for every reason CURATE is warranted on *state* (shown before or not)."""
    out: dict[str, str] = {}
    for c in state.overlap.get("candidates", []):
        out[c["fingerprint"]] = f"overlap ({c['rule']}): " + ", ".join(c["items"])
    for item in sorted(state.suspects):
        why = sorted(str(r) for r in (state.suspects[item] or {}).get("reasons", []))
        digest = hashlib.sha256(
            _canon([item, state.bodies.get(item, ""), why]).encode("utf-8"),
        ).hexdigest()
        out["suspect:" + digest] = f"suspect: {item}" + (
            f" ({'; '.join(why)})" if why else ""
        )
    if state.index_tokens is not None and state.index_tokens > budget:
        out[f"index:{state.commit}"] = (
            f"index: {state.index_tokens} tokens, over its {budget}-token view"
        )
    return out


def due(
    state: CurateState,
    seen: set[str],
    *,
    budget: int = INDEX_VIEW_TOKENS,
) -> dict[str, str]:
    """The reasons on *state* that no CURATE pass has been shown (spec §10.3); empty when CURATE is not due."""
    return {
        fp: line for fp, line in reasons(state, budget=budget).items() if fp not in seen
    }


def _write_json(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(obj, sort_keys=True, indent=1, ensure_ascii=False, default=str)
        + "\n",
    )


def _safe(rel: str) -> bool:
    parts = rel.split("/")
    return (
        bool(rel) and not rel.startswith("/") and ".." not in parts and "" not in parts
    )


def same_shape(bodies: dict[str, str]) -> list[list[str]]:
    """r5 S3: groups of library functions whose definitions are the same after renaming names and lifting
    literals (:mod:`.mining`'s tier (a)); each group sorted, groups sorted."""
    from .mining import _parse, keep_names, normalise

    by_key: dict[str, list[str]] = {}
    for item, body in sorted(bodies.items()):
        tree = _parse(body)
        if tree is None or not tree.body:
            continue
        key = normalise(tree.body[0], keep_names([tree]) | {item.rsplit(":", 1)[-1]})[0]
        by_key.setdefault(key, []).append(item)
    return sorted(group for group in by_key.values() if len(group) > 1)


def stage_inputs(inputs: Path, state: CurateState) -> list[str]:
    """Write CURATE's inputs under ``<inputs>/curate/`` (spec §12.3) and return their virtual paths, sorted.

    trigger.json (why this pass runs), overlap.json, suspects.json (with bisect results and rollback targets),
    use.json, history.json, aliases.json (each live alias, and whether this pass may remove it: one added by the
    pass that made this pass's parent stays) and, per suspect item with a rollback target,
    ``rollback/<n>/<path>`` holding that version's module and tests, listed in ``rollback/index.json``.
    """
    inputs = Path(inputs)
    root = inputs / CURATE_DIR
    _write_json(
        root / "trigger.json",
        {"commit": state.commit, "reasons": sorted(state.fired.values())},
    )
    # r5 S3: functions with the same shape, for merging (by structure; the use counts are in use.json)
    _write_json(root / "same_shape.json", {"groups": same_shape(state.bodies)})
    _write_json(root / "overlap.json", state.overlap)
    _write_json(root / "suspects.json", state.suspects)
    _write_json(root / "use.json", state.use)
    _write_json(root / "history.json", state.history)
    _write_json(
        root / "aliases.json",
        {
            a: {**row, "may_remove": row.get("commit") != state.commit}
            for a, row in sorted(state.aliases.items())
        },
    )
    index = []
    for n, item in enumerate(sorted(state.rollback_files)):
        files = {
            rel: data for rel, data in state.rollback_files[item].items() if _safe(rel)
        }
        for rel, data in sorted(files.items()):
            dest = root / "rollback" / str(n) / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
        index.append(
            {
                "item": item,
                "dir": f"/inputs/{CURATE_DIR}/rollback/{n}",
                "commit": (state.suspects.get(item) or {}).get("rollback"),
                "files": sorted(files),
            },
        )
    _write_json(root / "rollback" / "index.json", index)
    return sorted(
        "/inputs/" + p.relative_to(inputs).as_posix()
        for p in root.rglob("*")
        if p.is_file()
    )


def message(state: CurateState) -> str:
    """The CURATE part of the pass's first message: why it runs and where its inputs are."""
    lines = sorted(state.fired.values()) or ["(no reason recorded)"]
    return (
        "This CURATE pass runs because:\n"
        + "\n".join(f"- {line}" for line in lines)
        + "\n\nIts inputs are under /inputs/curate/: trigger.json, overlap.json, suspects.json, use.json, "
        "history.json, aliases.json and rollback/."
    )


def trailers(manifest: object) -> dict[str, list[str]]:
    """``Why:`` and ``Items:`` trailers of a CURATE commit (spec §10.4) from its manifest: the one-line why, and every
    item it adds, changes, deletes, aliases or retires. Values are one line each (a trailer holds no newline).
    """
    if not isinstance(manifest, dict):
        return {}
    out: dict[str, list[str]] = {}
    why = manifest.get("why")
    if isinstance(why, str) and why.strip():
        out["Why"] = [" ".join(why.split())[:300]]
    ids: set[str] = set()
    for it in manifest.get("items") or []:
        if isinstance(it, dict) and isinstance(it.get("item"), str):
            ids.add(it["item"])
    ids |= {x for x in manifest.get("deleted") or [] if isinstance(x, str)}
    for key in ("aliases", "retired"):
        if isinstance(manifest.get(key), dict):
            ids |= {x for x in manifest[key] if isinstance(x, str)}
    if ids:
        out["Items"] = sorted(" ".join(i.split())[:300] for i in ids)
    return out
