"""The memory v2.1 library layout (spec v2.1 §4.1–4.3): paths, item identity, note front matter, links as
written, discovery and the import graph. Pure: it reads and parses files and never runs library code.

One git repository, branch ``main``::

    memory/<package>/__init__.py              the package docstring (one paragraph) and imports only
    memory/<package>/<module>.py              functions; each public one is an item
    memory/<package>/tests/test_<module>.py   its tests (plain pytest)
    memory/<package>/tests/data/...           fixtures
    notes/<topic>/<slug>.md                   notes; each is an item

``memory/__init__.py``, ``INDEX.md``, ``links.json`` and ``.memory/`` are generated by the harness in every
copy of the library and are never committed (:mod:`.library_export`).

Item ids: a function is ``memory.<package>.<module>:<name>`` (a name starting with ``_`` is private and is not
an item); a note is its path, ``notes/<topic>/<slug>.md``. Links are written in two places only: a note's
``uses:`` list and a function docstring's ``Notes:`` line (:mod:`.library_index` derives both directions).
"""

from __future__ import annotations

import ast
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from .manifest import unsafe_path
from .memory_repo import _signature

PACKAGE_ROOT = "memory"
NOTES_ROOT = "notes"
RESERVED_INIT = "memory/__init__.py"
INDEX_FILE = "INDEX.md"
LINKS_FILE = "links.json"
DATA_DIR = ".memory"
GENERATED_ROOT_FILES = (RESERVED_INIT, INDEX_FILE, LINKS_FILE)
# Package names a subpackage import would bind over the helpers on ``memory`` (and P8's optional ones).
RESERVED_PACKAGES = frozenset({"index", "show", "find", "search", "suggest", "tests"})

_NAME = r"[a-z][a-z0-9_]*"
_SLUG = r"[a-z0-9][a-z0-9_-]*"
FUNCTION_ID = re.compile(rf"^memory\.({_NAME})\.({_NAME}):([A-Za-z][A-Za-z0-9_]*)\Z")
NOTE_ID = re.compile(rf"^notes/({_SLUG})/({_SLUG})\.md\Z")
_PACKAGE = re.compile(rf"^{_NAME}\Z")
_MODULE_FILE = re.compile(rf"^({_NAME})\.py\Z")
_TEST_FILE = re.compile(r"^test_[A-Za-z0-9_]*\.py\Z")
_NOTES_LINE = re.compile(r"^[ \t]*Notes:[ \t]*(.*)$", re.M)
FRONT_KEYS = ("title", "description", "uses")
ACTOR_KINDS = frozenset({"module", "package_init", "note"})


def classify(path: str) -> str | None:
    """What *path* (relative, POSIX) is in the v2.1 layout: ``module``, ``package_init``, ``test``,
    ``test_helper``, ``fixture``, ``note`` or ``generated``; None when the layout has no place for it, and
    always for a path with an empty, ``.`` or ``..`` component, a backslash or a NUL (Sol writes manifest paths).
    """
    if (
        not path
        or "\\" in path
        or "\x00" in path
        or any(c in ("", ".", "..") for c in path.split("/"))
    ):
        return None
    if (
        path in GENERATED_ROOT_FILES
        or path == DATA_DIR
        or path.startswith(DATA_DIR + "/")
    ):
        return "generated"
    parts = path.split("/")
    if parts[0] == PACKAGE_ROOT:
        if (
            len(parts) < 3
            or not _PACKAGE.match(parts[1])
            or parts[1] in RESERVED_PACKAGES
        ):
            return None
        if len(parts) == 3:
            if parts[2] == "__init__.py":
                return "package_init"
            m = _MODULE_FILE.match(parts[2])
            return "module" if m and m.group(1) != "tests" else None
        if parts[2] != "tests":
            return None
        rest = parts[3:]
        if rest[0] == "data":
            return "fixture" if len(rest) > 1 else None
        if len(rest) == 1 and _TEST_FILE.match(rest[0]):
            return "test"
        if len(rest) == 1 and rest[0].endswith(".py") and rest[0] != "__init__.py":
            return "test_helper"
        return None
    if parts[0] == NOTES_ROOT:
        return "note" if NOTE_ID.match(path) else None
    return None


def exported(path: str) -> bool:
    """Whether the actor's read-only copy holds committed *path* (spec §6): library modules, package
    docstrings and notes only. Never a tests directory or a fixture (§20 item 3), never a generated path (each
    copy writes its own), never compiled code or another G6 class, and never a path outside the layout.
    """
    found = unsafe_path(path)
    if found is not None and found[0] == "G6":
        return False
    return classify(path) in ACTOR_KINDS


def module_of(path: str) -> str | None:
    """The dotted module of a library module or package init, else None."""
    kind = classify(path)
    parts = path.split("/")
    if kind == "module":
        return f"memory.{parts[1]}.{parts[2][:-3]}"
    if kind == "package_init":
        return f"memory.{parts[1]}"
    return None


def module_path(module: str) -> str:
    """The file of a dotted library module (``memory.<package>`` is its package init)."""
    parts = module.split(".")
    if len(parts) == 2:
        return f"memory/{parts[1]}/__init__.py"
    return f"memory/{parts[1]}/{parts[2]}.py"


def item_path(item: str) -> str:
    """The file an item id lives in: a function's module, or a note's own path."""
    m = FUNCTION_ID.match(item)
    return f"memory/{m.group(1)}/{m.group(2)}.py" if m else item


def package_of_path(path: str) -> str:
    """The dotted package a file's relative imports resolve against: its directory."""
    return ".".join(path.split("/")[:-1])


# --- notes ---------------------------------------------------------------------------------------------------


class FrontMatterError(ValueError):
    pass


@dataclass
class NoteMeta:
    title: str
    description: str
    uses: list[str]
    body: str


def _scalar(raw: str) -> str:
    v = raw.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        v = v[1:-1]
    return v


def parse_front_matter(text: str) -> NoteMeta:
    """A note's front matter (spec §4.3), strictly. The file starts with a ``---`` line. Then come ``title:``
    and ``description:``, and optionally ``uses: [<item>, ...]``, one line each, each key once and no other
    key. A closing ``---`` line ends it. Raises :class:`FrontMatterError` naming what is wrong.
    """
    lines = text.split("\n")
    if lines[0].rstrip("\r") != "---":
        raise FrontMatterError("a note starts with a '---' line, then its front matter")
    end = next(
        (i for i in range(1, len(lines)) if lines[i].rstrip("\r") == "---"),
        None,
    )
    if end is None:
        raise FrontMatterError("the front matter has no closing '---' line")
    seen: dict[str, str] = {}
    for n, raw in enumerate(lines[1:end], 2):
        line = raw.rstrip("\r")
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        key = key.strip()
        if not sep or key not in FRONT_KEYS:
            raise FrontMatterError(
                f"line {n}: expected one of {', '.join(FRONT_KEYS)} followed by ':'",
            )
        if key in seen:
            raise FrontMatterError(f"line {n}: {key} is given twice")
        seen[key] = value
    for key in ("title", "description"):
        if not _scalar(seen.get(key, "")):
            raise FrontMatterError(f"the front matter needs a non-empty {key}")
    uses: list[str] = []
    raw_uses = seen.get("uses", "").strip()
    if raw_uses:
        if not (raw_uses.startswith("[") and raw_uses.endswith("]")):
            raise FrontMatterError("uses is a list on one line: uses: [<item>, <item>]")
        inner = raw_uses[1:-1].strip()
        uses = [_scalar(t) for t in inner.split(",")] if inner else []
        if any(not u for u in uses):
            raise FrontMatterError("uses holds an empty entry")
    return NoteMeta(
        _scalar(seen["title"]),
        _scalar(seen["description"]),
        uses,
        "\n".join(lines[end + 1 :]),
    )


def notes_links(doc: str) -> list[str]:
    """The note paths a function's docstring names on its ``Notes:`` line(s), as written, in order (one line,
    comma-separated; a token that is not a note path stays, and links.json marks it malformed).
    """
    out: list[str] = []
    for m in _NOTES_LINE.finditer(doc or ""):
        out += [t.strip() for t in m.group(1).split(",") if t.strip()]
    return out


# --- discovery -----------------------------------------------------------------------------------------------


@dataclass
class Function:
    item_id: str
    module: str
    name: str
    path: str
    lineno: int
    signature: str  # name(parameters) -> annotation, as v2's index wrote it
    summary: str  # the docstring's first line
    notes: list[str]  # the Notes: line's tokens, as written


@dataclass
class Note:
    item_id: str
    title: str
    description: str
    uses: list[str]
    error: str = ""  # why its front matter could not be read ("" when it was)


@dataclass
class Library:
    functions: list[Function] = field(default_factory=list)
    notes: list[Note] = field(default_factory=list)
    packages: dict[str, str] = field(
        default_factory=dict,
    )  # package -> its docstring's first sentence
    errors: list[str] = field(default_factory=list)


def first_sentence(doc: str) -> str:
    """The first sentence of a docstring's first paragraph, on one line."""
    para = " ".join((doc or "").strip().split("\n\n", 1)[0].split())
    m = re.search(r"[.!?](?=\s)", para)
    return para[: m.end()] if m else para


def _parse(path: Path) -> ast.Module | str:
    try:
        return ast.parse(path.read_bytes())
    except (SyntaxError, ValueError) as exc:
        return f"{type(exc).__name__}: {getattr(exc, 'msg', exc)}"


def _public_defs(module: ast.Module) -> list[ast.FunctionDef | ast.AsyncFunctionDef]:
    return [
        n
        for n in module.body
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
        and not n.name.startswith("_")
    ]


#: Why a file of the layout is not read: it is a link, or it resolves outside the library.
_REFUSED_LINK = "refused: a link or a path outside the library"


def _confined(tree: Path, p: Path) -> bool:
    """Whether *p* is a regular path of *tree*: not a link itself, and resolving inside *tree* (a linked
    directory on the way resolves outside). The harness never reads through a link Sol could commit.
    """
    root = os.path.realpath(tree)
    real = os.path.realpath(p)
    return not p.is_symlink() and (real == root or real.startswith(root + os.sep))


def _library_files(
    tree: Path,
    errors: list[str] | None = None,
) -> list[tuple[str, str]]:
    """(relative path, kind) of every module and package init of *tree*, in path order. A link, or a path
    resolving outside *tree*, is skipped (and named in *errors* when given)."""
    out = []
    for p in sorted(Path(tree).glob("memory/*/*.py")):
        rel = p.relative_to(tree).as_posix()
        kind = classify(rel)
        if kind in ("module", "package_init"):
            if not _confined(Path(tree), p):
                if errors is not None:
                    errors.append(f"{rel}: {_REFUSED_LINK}")
                continue
            out.append((rel, kind))
    return out


def discover(tree: Path) -> Library:
    """Every item of the library at *tree*, from the files alone (AST; nothing is imported or run)."""
    tree = Path(tree)
    lib = Library()
    for rel, kind in _library_files(tree, lib.errors):
        parsed = _parse(tree / rel)
        if isinstance(parsed, str):
            lib.errors.append(f"{rel}: {parsed}")
            continue
        pkg = rel.split("/")[1]
        if kind == "package_init":
            lib.packages[pkg] = first_sentence(ast.get_docstring(parsed) or "")
            continue
        lib.packages.setdefault(pkg, "")
        module = module_of(rel)
        seen: set[str] = set()
        for node in _public_defs(parsed):
            if node.name in seen:
                lib.errors.append(f"{rel}: {node.name} is defined more than once")
                continue
            seen.add(node.name)
            doc = ast.get_docstring(node) or ""
            lib.functions.append(
                Function(
                    f"{module}:{node.name}",
                    module,
                    node.name,
                    rel,
                    node.lineno,
                    _signature(node),
                    doc.strip().splitlines()[0] if doc.strip() else "",
                    notes_links(doc),
                ),
            )
    for p in sorted(tree.glob("notes/*/*.md")):
        rel = p.relative_to(tree).as_posix()
        if classify(rel) != "note":
            continue
        if not _confined(tree, p):
            lib.errors.append(f"{rel}: {_REFUSED_LINK}")
            continue
        try:
            meta = parse_front_matter(p.read_bytes().decode("utf-8"))
        except (FrontMatterError, UnicodeDecodeError) as exc:
            lib.notes.append(Note(rel, "", "", [], str(exc)[:200]))
            lib.errors.append(f"{rel}: {exc}"[:300])
            continue
        lib.notes.append(Note(rel, meta.title, meta.description, meta.uses))
    lib.packages = dict(sorted(lib.packages.items()))
    return lib


def module_bodies(source: bytes | str) -> dict[str, str]:
    """name -> unparsed definition of each public function of a module ({} when it does not parse)."""
    try:
        module = ast.parse(source)
    except (SyntaxError, ValueError):
        return {}
    out: dict[str, str] = {}
    for node in _public_defs(module):
        out.setdefault(node.name, ast.unparse(node))
    return out


def function_bodies(tree: Path) -> dict[str, str]:
    """item id -> unparsed definition of every function item of *tree*."""
    out: dict[str, str] = {}
    for rel, kind in _library_files(Path(tree)):
        if kind == "module":
            module = module_of(rel)
            for name, body in module_bodies((Path(tree) / rel).read_bytes()).items():
                out[f"{module}:{name}"] = body
    return out


# --- imports -------------------------------------------------------------------------------------------------


def library_modules(tree: Path) -> set[str]:
    """The dotted names of every library module and package init of *tree*."""
    return {module_of(rel) for rel, _ in _library_files(Path(tree))}


def _package(module: str) -> str:
    return module if module.count(".") == 1 else module.rsplit(".", 1)[0]


def _resolve(package: str, node: ast.ImportFrom) -> str | None:
    if node.level == 0:
        return node.module
    parts = package.split(".")
    if node.level > len(parts):
        return None
    base = parts[: len(parts) - node.level + 1]
    return ".".join(base + ([node.module] if node.module else []))


def imports(
    source: bytes,
    package: str,
    modules: set[str],
) -> tuple[set[str], set[str]] | None:
    """What *source* imports from the library. Returns two sets:

    - the item ids it imports by name (``from memory.a.b import f`` gives ``memory.a.b:f``);
    - the modules it imports whole: ``import memory.a.b``, ``from memory.a import b``, a star import, and every
      package init that runs on the way.

    Relative imports resolve against *package*. Only names in *modules* (:func:`library_modules`) count.
    Returns None when *source* does not parse.
    """
    try:
        tree = ast.parse(source)
    except (SyntaxError, ValueError):
        return None
    names: set[str] = set()
    whole: set[str] = set()

    def prefixes(dotted: str, *, include_last: bool) -> None:
        parts = dotted.split(".")
        for i in range(2, len(parts) + (1 if include_last else 0)):
            if ".".join(parts[:i]) in modules:
                whole.add(".".join(parts[:i]))

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] == PACKAGE_ROOT:
                    prefixes(a.name, include_last=True)
        elif isinstance(node, ast.ImportFrom):
            base = _resolve(package, node)
            if base is None or base.split(".")[0] != PACKAGE_ROOT:
                continue
            prefixes(base, include_last=False)
            if base in modules and base.count(".") == 1:
                whole.add(base)  # a package init runs on import
            for a in node.names:
                sub = f"{base}.{a.name}"
                if sub in modules:
                    whole.add(sub)
                elif a.name == "*" or base.count(".") == 1:
                    if base in modules:
                        whole.add(base)
                elif base in modules:
                    names.add(f"{base}:{a.name}")
    return names, whole


def import_graph(tree: Path) -> dict[str, set[str]]:
    """Library module (or package init) -> the library modules its code imports, directly."""
    tree = Path(tree)
    modules = library_modules(tree)
    graph: dict[str, set[str]] = {}
    for m in sorted(modules):
        refs = imports((tree / module_path(m)).read_bytes(), _package(m), modules)
        names, whole = refs if refs is not None else (set(), set())
        graph[m] = (whole | {n.split(":", 1)[0] for n in names}) - {m}
    return graph


def merge_graphs(a: dict[str, set[str]], b: dict[str, set[str]]) -> dict[str, set[str]]:
    """The union of two import graphs (an edge in either version counts)."""
    out = {m: set(t) for m, t in a.items()}
    for m, t in b.items():
        out.setdefault(m, set()).update(t)
    return out


def imported_closure(graph: dict[str, set[str]], module: str) -> set[str]:
    """*module* and every library module it imports, directly or through others."""
    seen, todo = {module}, [module]
    while todo:
        for n in graph.get(todo.pop(), ()):
            if n not in seen:
                seen.add(n)
                todo.append(n)
    return seen


def dependants(graph: dict[str, set[str]], changed: set[str]) -> set[str]:
    """*changed* with every module that imports one of them, directly or through others (spec §4.1, D42)."""
    reverse: dict[str, set[str]] = {}
    for m, targets in graph.items():
        for t in targets:
            reverse.setdefault(t, set()).add(m)
    seen, todo = set(changed), list(changed)
    while todo:
        for n in reverse.get(todo.pop(), ()):
            if n not in seen:
                seen.add(n)
                todo.append(n)
    return seen
