"""links.json and INDEX.md for a v2.1 library (spec §4.3, §4.5), and the index view the prompt carries.

Both are generated by the harness for every copy of the library, from the tree and the item statuses (P5's
records; ``experimental`` until then). A model never writes them. The same inputs give the same bytes:
everything is sorted, and nothing depends on time, paths or the order files were written in. ``links.json``
holds every item, hidden ones included. ``INDEX.md`` leaves out ``suspect`` and ``deprecated`` items, which
stay reachable through ``memory.show``.

The view rule (P5): the prompt carries the whole index up to :data:`INDEX_VIEW_TOKENS`. Past that it carries
the section headings with item counts, and ``memory.index("<section>")`` prints any section in full. Nothing
is ever cut silently, and the collapsed view is never cut further: growth past the budget is CURATE's to fix
(spec §10.3, P6).
"""

from __future__ import annotations

import json
from collections.abc import Callable

from .catalogue import estimate_tokens
from .layout import FUNCTION_ID, NOTE_ID, Library
from .library_helper import item_count, section_key, split_index

INDEX_VIEW_TOKENS = 4000
STATUSES = ("experimental", "stable", "suspect", "deprecated")
HIDDEN = frozenset({"suspect", "deprecated"})
StatusOf = Callable[[str], str]
INDEX_HEAD = (
    "# Memory index\n\n"
    "Generated by the harness from the library; never edit it. One line per item: a function as "
    "`memory.<package>.<module>:<name>(<parameters>)`, a note as `notes/<topic>/<slug>.md`, each with its "
    'status in brackets and the items it links to either way. `memory.show("<item>")` shows one in full.\n'
)
_EMPTY = "\nThe library is empty.\n"


def experimental(item: str) -> str:
    return "experimental"


def _status(status_of: StatusOf | None, item: str) -> str:
    s = (status_of or experimental)(item)
    if s not in STATUSES:
        raise ValueError(f"unknown status {s!r} for {item}")
    return s


def build_links(lib: Library) -> dict:
    """Every item's links both ways (spec §4.3), and each written link that names no item of the right kind.

    A function links to the notes its ``Notes:`` line names. A note links to the functions its ``uses:`` list
    names. ``linked_from`` is derived from those. A dangling link names its source, its target and why:
    ``missing`` (well formed, no such item), ``malformed`` (not an id of the kind it must name) or ``not a
    <kind>``.
    """
    items: dict[str, dict] = {}
    for f in lib.functions:
        items[f.item_id] = {
            "kind": "function",
            "path": f.path,
            "links_to": sorted(set(f.notes)),
            "linked_from": [],
        }
    for n in lib.notes:
        items[n.item_id] = {
            "kind": "note",
            "path": n.item_id,
            "links_to": sorted(set(n.uses)),
            "linked_from": [],
        }
    dangling: list[dict] = []
    for src in sorted(items):
        want = "note" if items[src]["kind"] == "function" else "function"
        pattern = NOTE_ID if want == "note" else FUNCTION_ID
        for dst in items[src]["links_to"]:
            target = items.get(dst)
            if target is None:
                why = "missing" if pattern.match(dst) else "malformed"
                dangling.append({"from": src, "to": dst, "why": why})
            elif target["kind"] != want:
                dangling.append({"from": src, "to": dst, "why": f"not a {want}"})
            else:
                target["linked_from"].append(src)
    for row in items.values():
        row["linked_from"].sort()
    return {"version": 1, "items": items, "dangling": dangling}


def render_links(links: dict) -> str:
    """``links.json``: sorted keys, one trailing newline."""
    return json.dumps(links, sort_keys=True, indent=1, ensure_ascii=False) + "\n"


def _linked(links: dict, item: str, kind: str, shown: set[str]) -> list[str]:
    row = links["items"][item]
    both = set(row["links_to"]) | set(row["linked_from"])
    return sorted(i for i in both if i in shown and links["items"][i]["kind"] == kind)


def render_index(lib: Library, links: dict, status_of: StatusOf | None = None) -> str:
    """``INDEX.md`` (spec §4.5): one section per package that lists a function (heading: its docstring's first
    sentence) and one per notes topic that lists a note. Each function line gives its id with its signature,
    its summary, its status and its notes. Each note line gives its path, its description, its status and its
    functions."""
    status = {i: _status(status_of, i) for i in links["items"]}
    shown = {i for i, s in status.items() if s not in HIDDEN}
    by_pkg: dict[str, list[str]] = {}
    for f in sorted(lib.functions, key=lambda f: f.item_id):
        if f.item_id not in shown:
            continue
        line = (
            f"- `{f.module}:{f.signature}`"
            + (f" — {f.summary}" if f.summary else "")
            + f" [{status[f.item_id]}]"
        )
        notes = _linked(links, f.item_id, "note", shown)
        if notes:
            line += "; notes: " + ", ".join(notes)
        by_pkg.setdefault(f.module.split(".")[1], []).append(line)
    by_topic: dict[str, list[str]] = {}
    for n in sorted(lib.notes, key=lambda n: n.item_id):
        if n.item_id not in shown:
            continue
        about = (
            n.description if not n.error else f"(front matter unreadable: {n.error})"
        )
        line = f"- `{n.item_id}` — {about} [{status[n.item_id]}]"
        fns = _linked(links, n.item_id, "function", shown)
        if fns:
            line += "; functions: " + ", ".join(fns)
        by_topic.setdefault(n.item_id.split("/")[1], []).append(line)
    out = [INDEX_HEAD]
    for pkg in sorted(by_pkg):
        summary = lib.packages.get(pkg, "")
        out.append(
            f"\n## memory.{pkg}"
            + (f" — {summary}" if summary else "")
            + "\n\n"
            + "\n".join(by_pkg[pkg])
            + "\n",
        )
    for topic in sorted(by_topic):
        out.append(f"\n## notes/{topic}\n\n" + "\n".join(by_topic[topic]) + "\n")
    if not by_pkg and not by_topic:
        out.append(_EMPTY)
    return "".join(out)


def index_view(index: str, budget_tokens: int = INDEX_VIEW_TOKENS) -> str:
    """What the prompt carries of *index* (P5): all of it within *budget_tokens*, else its head and each
    section's heading with its item count, and how to print a section."""
    total = estimate_tokens(index)
    if total <= budget_tokens:
        return index
    head, sections = split_index(index)
    first = section_key(sections[0][0]) if sections else "memory.<package>"
    out = [
        head,
        f"\nThis index is {total} tokens, over the {budget_tokens} shown here, so each section below gives "
        f'only its item count. `memory.index("<section>")` prints one section in full (for example '
        f'`memory.index("{first}")`), and INDEX.md holds all of it.\n',
    ]
    for heading, body in sections:
        n = item_count(body)
        word = "note" if heading.startswith("notes/") else "function"
        out.append(f"\n## {heading} ({n} {word}{'' if n == 1 else 's'})\n")
    return "".join(out)


def listed(index: str) -> int:
    """How many items an index lists."""
    return sum(item_count(body) for _, body in split_index(index)[1])


def packages_of(index: str) -> list[str]:
    """The packages an index has sections for, sorted (the names the use record keeps)."""
    keys = [section_key(h) for h, _ in split_index(index)[1]]
    return sorted({k.split(".", 1)[1] for k in keys if k.startswith("memory.")})
