"""The generated files of every v2.1 library copy (spec v2.1 §4.1–4.5, §6): the actor's export and Sol's box.

* ``memory/__init__.py``: :mod:`.library_helper`, byte for byte (``index``, ``show``, ``find``);
* ``INDEX.md`` and ``links.json``: :mod:`.library_index`;
* ``.memory/items.json``: what ``show`` reads per item, namely its kind, path, signature or title, status, the
  verification and use records (None until P5) and the subjects of the commits that changed it;
* ``.memory/find.json``: the listed functions with their recorded input shapes, keyed by body digest
  (:mod:`.shape_rows`);
* ``.memory/matcher.py``: v2's matcher (:mod:`.memory_helper` up to its catalogue section, so none of v2's
  catalogue or its footer ships);
* ``.memory/shapes.py``: :mod:`.analysis.shapes`, byte for byte.

None of these is ever committed (D13; P4's G1 refuses them). Each is a pure function of the tree, the item
statuses, the recorded shapes and the history, so the same commit gives the same bytes (cache rule).
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

from .catalogue import ShapeLookup, body_digest
from .gitio import GitError, Repo
from .layout import (
    INDEX_FILE,
    LINKS_FILE,
    RESERVED_INIT,
    Library,
    classify,
    discover,
    function_bodies,
    module_bodies,
    module_of,
)
from .library_helper import FIND_FILE, ITEMS_FILE, MATCHER_FILE, SHAPES_FILE
from .library_index import HIDDEN, build_links, render_index, render_links
from .redact import redact_error

HISTORY_SCAN = 200
HISTORY_SHOW = 5
_MATCHER_START = "from __future__ import annotations"
_MATCHER_END = "\n# --- the catalogue"
_HERE = Path(__file__).resolve().parent
History = tuple[dict[str, list[str]], bool]


def matcher_source() -> bytes:
    """v2's shape matcher without its module docstring or catalogue (``memory_helper.py`` from its imports up to
    the ``# --- the catalogue`` section), behind a one-line docstring."""
    src = (_HERE / "memory_helper.py").read_text(encoding="utf-8")
    body = src[src.index(_MATCHER_START) : src.index(_MATCHER_END) + 1]
    return (
        '"""Shape matching for memory.find; generated by the harness, never edit it."""\n\n'
        + body
    ).encode("utf-8")


def _bodies(repo: Repo, rev: str | None, path: str) -> dict[str, str]:
    if rev is None:
        return {}
    try:
        return module_bodies(repo.show(rev, path))
    except GitError:
        return {}


def item_history(repo: Repo, sha: str, *, scan: int = HISTORY_SCAN) -> History:
    """item id -> ``"<sha12> <subject>"`` of each of the newest *scan* commits up to *sha* that changed it
    (newest first), and whether that scan reached every such commit.

    A function changes when its unparsed definition differs from its parent's (what ``git log -L`` follows,
    computed by AST instead of git's function-name heuristics). A note changes when its file changes.
    Each subject is redacted (:func:`..redact.redact_error`): ``show`` prints it to the actor, and a commit
    may have come from any merge path.
    """
    raw = repo.run(
        "log",
        f"--max-count={scan + 1}",
        "--format=%H%x1f%P%x1f%s",
        sha,
        "--",
        "memory",
        "notes",
    )
    rows = [line.split("\x1f", 2) for line in raw.splitlines() if line]
    out: dict[str, list[str]] = {}
    for commit, parents, subject in rows[:scan]:
        parent = parents.split()[0] if parents.split() else None
        changed = repo.run(
            "diff-tree",
            "--no-commit-id",
            "--name-only",
            "-r",
            "--root",
            "-z",
            commit,
            "--",
            "memory",
            "notes",
        )
        for path in (p for p in changed.split("\0") if p):
            kind = classify(path)
            if kind == "note":
                ids = {path}
            elif kind == "module":
                before, after = _bodies(repo, parent, path), _bodies(repo, commit, path)
                module = module_of(path)
                ids = {
                    f"{module}:{n}"
                    for n in set(before) | set(after)
                    if before.get(n) != after.get(n)
                }
            else:
                continue
            for item in sorted(ids):
                out.setdefault(item, []).append(
                    f"{commit[:12]} {redact_error(subject)}",
                )
    return out, len(rows) <= scan


def _status(status_of: Callable[[str], str] | None, item: str) -> str:
    return status_of(item) if status_of is not None else "experimental"


def items_data(
    lib: Library,
    status_of: Callable[[str], str] | None,
    history: dict[str, list[str]],
    complete: bool,
) -> dict:
    """``.memory/items.json``: everything :func:`.library_helper.show` needs that the files do not hold."""
    rows: dict[str, dict] = {}

    def common(item: str) -> dict:
        h = history.get(item, [])
        return {
            "status": _status(status_of, item),
            "status_reason": None,  # P5: why an item is suspect or deprecated
            "verification": None,  # P5: the item record's verification summary
            "use": None,  # P5: the item record's use summary
            "history": h[:HISTORY_SHOW],
            "history_more": max(0, len(h) - HISTORY_SHOW),
        }

    for f in lib.functions:
        rows[f.item_id] = {
            "kind": "function",
            "path": f.path,
            "signature": f"{f.module}:{f.signature}",
            "summary": f.summary,
            **common(f.item_id),
        }
    for n in lib.notes:
        rows[n.item_id] = {
            "kind": "note",
            "path": n.item_id,
            "title": n.title,
            "description": n.description,
            "error": n.error,
            **common(n.item_id),
        }
    return {
        "version": 1,
        "items": rows,
        "history_complete": complete,
        "history_scanned": HISTORY_SCAN,
    }


def find_data(
    tree: Path,
    lib: Library,
    status_of: Callable[[str], str] | None,
    shapes: ShapeLookup | None,
) -> dict:
    """``.memory/find.json``: each listed function with the recorded input shapes of its current body."""
    bodies = function_bodies(tree) if shapes is not None else {}
    out: list[dict] = []
    for f in lib.functions:
        if _status(status_of, f.item_id) in HIDDEN:
            continue
        entry = {
            "id": f.item_id,
            "module": f.module,
            "name": f.name,
            "signature": f.signature,
            "input": "",
            "summary": f.summary,
        }  # input: the item record's form, from P5
        if shapes is not None and f.item_id in bodies:
            found = shapes(f.item_id, body_digest(bodies[f.item_id]))
            if found and found[0]:
                entry["input_shapes"] = found[0]
        out.append(entry)
    return {"version": 1, "functions": out}


def _json_bytes(data: dict) -> bytes:
    return (
        json.dumps(data, sort_keys=True, indent=1, ensure_ascii=False) + "\n"
    ).encode("utf-8")


def generated_v21(
    tree: Path,
    *,
    status_of: Callable[[str], str] | None = None,
    shapes: ShapeLookup | None = None,
    history: History | None = None,
) -> dict[str, bytes]:
    """Every generated file of the copy of the library at *tree*, by relative path (module docstring)."""
    tree = Path(tree)
    lib = discover(tree)
    links = build_links(lib)
    found, complete = history if history is not None else ({}, True)
    return {
        RESERVED_INIT: (_HERE / "library_helper.py").read_bytes(),
        INDEX_FILE: render_index(lib, links, status_of).encode("utf-8"),
        LINKS_FILE: render_links(links).encode("utf-8"),
        ITEMS_FILE: _json_bytes(items_data(lib, status_of, found, complete)),
        FIND_FILE: _json_bytes(find_data(tree, lib, status_of, shapes)),
        MATCHER_FILE: matcher_source(),
        SHAPES_FILE: (_HERE / "analysis" / "shapes.py").read_bytes(),
    }
