"""The builtin guidance library: the committed snapshot and its seeding.

``builtins_guidance.json`` next to this module is generated by
``scripts.skill_migration.builtins_import`` from upstream Agent Skills
repositories pinned in a lockfile manifest. Its entries are seeded into the
``builtin_guidance`` table, which the assistant's own guidance reads
alongside (through the ``all_guidance`` view) and never writes to.

Builtin rows carry stable hash-based ``guidance_id`` values derived from the
namespaced title, so they never collide with the auto-incrementing ids of the
user's own entries.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Dict, Optional

from unify import db

SNAPSHOT_PATH = Path(__file__).with_name("builtins_guidance.json")

_SEEDED_FOR: set[str] = set()


def stable_guidance_id(title: str) -> int:
    """Derive the stable builtin guidance id from a namespaced title.

    First 4 bytes of SHA-256, masked to the signed int32 range (mirrors
    primitive function ids).
    """
    digest = hashlib.sha256(title.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], "big") & 0x7FFFFFFF


def load_snapshot(path: Optional[Path] = None) -> Dict[str, Dict[str, str]]:
    """Load the committed snapshot (skill key → ``{"title", "content"}``)."""
    path = path or SNAPSHOT_PATH
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8")).get("skills", {})


def seed_builtin_guidance(
    *,
    entries: Optional[Dict[str, Dict[str, str]]] = None,
) -> bool:
    """Make the ``builtin_guidance`` table equal to ``entries`` (default: the snapshot).

    Returns True when any row was inserted, changed or removed.
    """
    entries = load_snapshot() if entries is None else entries
    desired = {
        stable_guidance_id(entry["title"]): (entry["title"], entry["content"])
        for entry in entries.values()
    }
    stored = {
        row["guidance_id"]: (row["title"], row["content"])
        for row in db.query("SELECT guidance_id, title, content FROM builtin_guidance")
    }
    if stored == desired:
        return False
    with db.transaction() as conn:
        conn.execute("DELETE FROM builtin_guidance")
        conn.executemany(
            "INSERT INTO builtin_guidance (guidance_id, title, content) VALUES (?, ?, ?)",
            [(gid, title, content) for gid, (title, content) in desired.items()],
        )
    return True


def builtin_guidance_enabled() -> bool:
    """False under ``UNIFY_BUILTIN_GUIDANCE=0``: the catalogue is neither seeded nor read."""
    from unify.settings import SETTINGS

    return bool(SETTINGS.UNIFY_BUILTIN_GUIDANCE)


def ensure_seeded() -> None:
    """Seed the snapshot once per process for the store currently open."""
    if not builtin_guidance_enabled():
        return
    path = db.store_path()
    if path in _SEEDED_FOR:
        return
    seed_builtin_guidance()
    _SEEDED_FOR.add(path)


__all__ = [
    "SNAPSHOT_PATH",
    "builtin_guidance_enabled",
    "ensure_seeded",
    "load_snapshot",
    "seed_builtin_guidance",
    "stable_guidance_id",
]
